language: node_js
script: make test-sauce
node_js:
  - '0.10'
env:
  global:
    - secure: DB2wQz4E2uN/GH4nm8jqjaNFWHwxtnR8HRKBianwdix0HU2R/wKKV3te7dLndPLsZXedNQmeWw7/b453yFvIoWp++bt5G89qV0lRPINCYmkZaxBYEVMDdAlcwgffQX+Xf5KoLXkV7pb4cFpKtiTq4ZNXNyi3eDmD43+B1NdifI0=
    - secure: tqNx+rpmlxlN2wVr8aeFWanVV+Nf03zHxnnbDS7T9gIebaegicRzW40NHU6WO3+aAVlwXl+GvluIAmad9+/T2mKIRT4kU/sZRdbQyQvdE7QieG0n/uDf+Dk4AVHvm9FVTjj0rHrhllV5HFsH/pbMM4PJKMwEOAUFYAZfUoESa5Y=
  matrix:
    - BROWSER: chrome
    - BROWSER: safari
    - BROWSER: firefox
    - BROWSER: ie8..11
